databases:
  - name: mysitedb
    plan: free
    databaseName: myDatabaseName
    user: myDatabaseUser

services:
  - type: web
    plan: free
    name: myDatabaseService
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn bookproject.asgi:application -k uvicorn.workes.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionsString
      - key: WEB_CONCURRENCE
        value: 4